Document: lombok-ast
Title: Debian lombok-ast Manual
Author: <insert document author here>
Abstract: This manual describes what lombok-ast is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lombok-ast/lombok-ast.sgml.gz

Format: postscript
Files: /usr/share/doc/lombok-ast/lombok-ast.ps.gz

Format: text
Files: /usr/share/doc/lombok-ast/lombok-ast.text.gz

Format: HTML
Index: /usr/share/doc/lombok-ast/html/index.html
Files: /usr/share/doc/lombok-ast/html/*.html
